### PR TITLE
OTel GenAI semconv fix +  anthropic automatic prompt caching 

### LINKED ISSUE #1571: bug:  wrong OTel GenAI span attribute names for cache token usage
Rig emits non-compliant span attributes for cache tokens.

| Current | OTel spec |
|---|---|
| `gen_ai.usage.cached_tokens` | `gen_ai.usage.cache_read.input_tokens` |
| *(not recorded)* | `gen_ai.usage.cache_creation.input_tokens` |

Affects all providers via `telemetry/mod.rs` → `record_token_usage`.

**Ref:** https://opentelemetry.io/docs/specs/semconv/gen-ai/anthropic/

### PR DESCRIPTION
**Pull request by lgaches**
Fix #1571 

 **OTel GenAI semconv compliance**

Rig emits non-compliant span attribute names for cache tokens, breaking interoperability with OTel-aware backends (Honeycomb, Grafana, Langfuse, etc.).

| Current | OTel spec |
|---|---|
| `gen_ai.usage.cached_tokens` | `gen_ai.usage.cache_read.input_tokens` |
| *(not recorded)* | `gen_ai.usage.cache_creation.input_tokens` |
| `input + cache_read + cache_creation` for `gen_ai.usage.input_tokens` | base `input_tokens` only |

The wrong field name affects **all providers** via the shared `record_token_usage` in `telemetry/mod.rs`. The missing `cache_creation` field and inflated `input_tokens` are Anthropic-specific.

**References**
- https://opentelemetry.io/docs/specs/semconv/gen-ai/anthropic/

**Anthropic Automatic prompt caching**

New builder methods — no beta header required:
```
// 5-min TTL (default)
client.completion_model("claude-sonnet-4-5").with_automatic_caching();

// 1-hour TTL (requires extended-cache-ttl-2025-04-11 beta header)
client.completion_model("claude-sonnet-4-5").with_automatic_caching_1h();
```

### CODE REVIEW

File: rig/rig-core/src/completion/request.rs [hunk 1]
```diff
@@ -409,8 +409,10 @@ pub struct Usage {
     pub output_tokens: u64,
     /// We store this separately as some providers may only report one number
     pub total_tokens: u64,
-    /// The number of cached input tokens (from prompt caching). 0 if not reported by provider.
+    /// The number of input tokens read from a provider-managed cache
     pub cached_input_tokens: u64,
+    /// The number of input tokens written to a provider-managed cache
+    pub cache_creation_input_tokens: u64,
```
Comment (joshua-mo-143) [inline rig/rig-core/src/completion/request.rs:415]: I wonder if we should make cached creation input tokens Option<u64> since only Anthropic really supports this.

**Review by joshua-mo-143 — CHANGES_REQUESTED** [review]
See comment. lgtm otherwise

File: rig/rig-core/src/completion/request.rs (hunk 1 above)
Comment (lgaches) [reply rig/rig-core/src/completion/request.rs:415]: consistent with `cached_input_tokens`  and no option noise.
