### PR TITLE
fix(rig-761): ollama drops tool call results

### LINKED ISSUE #477: bug: ollama drops tool call results
> The ollama provider also drops `ToolResult`s. This is pretty obvious if you look at the code, but wasn't mentioned in the issue description. 

 _Originally posted by @lnicola in [#446](https://github.com/0xPlaygrounds/rig/issues/446#issuecomment-2926668421)_

Looks like this got missed in the PR - we'll be fixing this very, very soon.

### PR DESCRIPTION
**Pull request by joshua-mo-143**

### CODE REVIEW

File: rig-core/src/providers/ollama.rs [hunk 1]
```diff
@@ -615,6 +616,31 @@ impl TryFrom<crate::message::Message> for Message {
                     match uc {
                         crate::message::UserContent::Text(t) => texts.push(t.text),
                         crate::message::UserContent::Image(img) => images.push(img.data),
+                        crate::message::UserContent::ToolResult(result) => {
+                            let crate::message::ToolResultContent::Text(_) = result.content.first()
```
Comment (lnicola) [inline rig-core/src/providers/ollama.rs]: I think this check duplicates the `collect` below, so there's no need for it.

**Review by lnicola — APPROVED** [review]

**Comment by andrewwebber** [comment]
I hope my comments/feedback are in some way helpful. I welcomed initially viewing this MR after addressing the same issue locally for one week now :) 

I tried running this branch but unfortunately still experience issues

```bash
Error: CompletionError: ProviderError: {"error":"json: cannot unmarshal array into Go struct field ChatRequest.messages.content of type string"}

Caused by:
    ProviderError: {"error":"json: cannot unmarshal array into Go struct field ChatRequest.messages.content of type string"}
```

From my limited understanding this is due to the fields expected in the Ollama API. I am currently testing with version **0.9.0** 

It wasnt until I made the following primitive changes that everything worked for me.

```diff
--- a/rig-core/src/providers/ollama.rs
+++ b/rig-core/src/providers/ollama.rs
@@ -593,10 +593,7 @@ pub enum Message {
         name: Option<String>,
     },
     #[serde(rename = "Tool")]
-    ToolResult {
-        tool_call_id: String,
-        content: OneOrMany<ToolResultContent>,
-    },
+    ToolResult { name: String, content: String },
 }
 
 /// -----------------------------
@@ -630,8 +627,8 @@ impl TryFrom<crate::message::Message> for Message {
                             })?;
 
                             return Ok(Message::ToolResult {
-                                tool_call_id: result.id,
-                                content,
+                                name: result.id,
+                                content: content.first().text,
                             });
                         }
                         _ => {} // Audio variant removed since Ollama API does not support it.
@@ -716,13 +713,10 @@ impl From<Message> for crate::completion::Message {
                     text: content,
                 })),
             },
-            Message::ToolResult {
-                tool_call_id,
-                content,
-            } => crate::completion::Message::User {
+            Message::ToolResult { name, content } => crate::completion::Message::User {
                 content: OneOrMany::one(message::UserContent::tool_result(
-                    tool_call_id,
-                    content.map(|content| message::ToolResultContent::text(content.text)),
+                    name,
+                    OneOrMany::one(message::ToolResultContent::text(content)),
                 )),
             },
         }
```

This was tested with the following **Tools** example

<details>
  <summary>Agent with Tools Example</summary>
<code>

use anyhow::Result;
use rig::{
    cli_chatbot::cli_chatbot,
    completion::{Prompt, ToolDefinition},
    providers,
    tool::Tool,
};
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Deserialize)]
struct OperationArgs {
    location: String,
}

#[derive(Debug, thiserror::Error)]
#[error("Math error")]
struct MathError;

#[derive(Deserialize, Serialize)]
struct Weather;
impl Tool for Weather {
    const NAME: &'static str = "weather";

    type Error = MathError;
    type Args = OperationArgs;
    type Output = String;

    async fn definition(&self, _prompt: String) -> ToolDefinition {
        ToolDefinition {
            name: "weather".to_string(),
            description: "Get the weather for a given location".to_string(),
            parameters: json!({
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The location to retreive weather information"
                    }
                }
            }),
        }
    }

    async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
        println!("[tool-call] looking up {} ", args.location);
        if args.location.is_empty() {
            return Ok("".to_string());
        }

        let result = "heavy snow".to_string();

        Ok(result)
    }
}

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::DEBUG)
        .with_target(false)
        .init();

    // Create OpenAI client
    let openai_client = providers::ollama::Client::new();

    // Create agent with a single context prompt and two tools
    let calculator_agent = openai_client
        .agent(providers::ollama::LLAMA3_2)
        .preamble("You are a weather assistant here to help the user perform weather operations. Use the tools provided, when appropriate, to answer the user's question.")
        .max_tokens(1024)
        .tool(Weather)
        .build();

    // Prompt the agent and print the response
    let prompt = "What is the weather on Mars. Tell me a joke about the result";
    println!("{prompt}");
    println!(
        "OpenAI Weather Agent: {}",
        calculator_agent
            .prompt(prompt)
            // .multi_turn(1)
            .await?
    );
    // cli_chatbot(calculator_agent).await?;

    Ok(())
}

</code>
</details>

**Comment by joshua-mo-143** [comment]
> I hope my comments/feedback are in some way helpful. I welcomed initially viewing this MR after addressing the same issue locally for one week now :)
> 
> I tried running this branch but unfortunately still experience issues
> 
> ```shell
> Error: CompletionError: ProviderError: {"error":"json: cannot unmarshal array into Go struct field ChatRequest.messages.content of type string"}
> 
> Caused by:
>     ProviderError: {"error":"json: cannot unmarshal array into Go struct field ChatRequest.messages.content of type string"}
> ```
> 
> From my limited understanding this is due to the fields expected in the Ollama API. I am currently testing with version **0.9.0**
> 
> It wasnt until I made the following primitive changes that everything worked for me.
> 
> ```diff
> --- a/rig-core/src/providers/ollama.rs
> +++ b/rig-core/src/providers/ollama.rs
> @@ -593,10 +593,7 @@ pub enum Message {
>          name: Option<String>,
>      },
>      #[serde(rename = "Tool")]
> -    ToolResult {
> -        tool_call_id: String,
> -        content: OneOrMany<ToolResultContent>,
> -    },
> +    ToolResult { name: String, content: String },
>  }
>  
>  /// -----------------------------
> @@ -630,8 +627,8 @@ impl TryFrom<crate::message::Message> for Message {
>                              })?;
>  
>                              return Ok(Message::ToolResult {
> -                                tool_call_id: result.id,
> -                                content,
> +                                name: result.id,
> +                                content: content.first().text,
>                              });
>                          }
>                          _ => {} // Audio variant removed since Ollama API does not support it.
> @@ -716,13 +713,10 @@ impl From<Message> for crate::completion::Message {
>                      text: content,
>                  })),
>              },
> -            Message::ToolResult {
> -                tool_call_id,
> -                content,
> -            } => crate::completion::Message::User {
> +            Message::ToolResult { name, content } => crate::completion::Message::User {
>                  content: OneOrMany::one(message::UserContent::tool_result(
> -                    tool_call_id,
> -                    content.map(|content| message::ToolResultContent::text(content.text)),
> +                    name,
> +                    OneOrMany::one(message::ToolResultContent::text(content)),
>                  )),
>              },
>          }
> ```
> 
> This was tested with the following **Tools** example
> 
> Agent with Tools Example

Thanks for reaching out! Ollama is quite confusing... I wish they had better docs :sweat_smile:

**Comment by lnicola** [comment]
The openai provider works well with ollama, so when in doubt you can do the same. I do seem to remember seeing tool call ids in the responses, though.

**Comment by joshua-mo-143** [comment]
> The openai provider works well with ollama, so when in doubt you can do the same. I do seem to remember seeing tool call ids in the responses, though.

Yeah, the tool calling differs unfortunately. Pretty much every provider says they're OpenAI compatible until they aren't

**Comment by lnicola** [comment]
I mean, I'm using rig with the openai provider and ollama and it appears to work. It's just that the smaller models have trouble. I couldn't get anything under 14b to use tools reliably.

**Comment by andrewwebber** [comment]
I am currently testing all samples with the Ollama provider. Thank you @lnicola for the suggestion to test using the OpenAI provider instead.

I am interested in testing Tools with Ollama to eventually explore MCP integrations via Tools. Although I am not understand how the rest of the MCP resources fit into the Rig Architecture (e.g. Prompts and Resources).

Looking at the Ollama docs, perhaps a list of tools used needs to be eventually sent on the completion request as it looks like Rig's architecture suggests that multiple Tools could be requested by the model for any given prompt. 

In my case I made some embarrassing hacks that worked for me but I am sure are at a professional level for this project.

As I am poor (8GB VRAM),  I am testing the following models where, with my patches,  I have been successful :
- llama3.2:3b
- qwen3:4b
- qwen3:8b

**Comment by joshua-mo-143** [comment]
> I am currently testing all samples with the Ollama provider. Thank you @lnicola for the suggestion to test using the OpenAI provider instead.
> 
> I am interested in testing Tools with Ollama to eventually explore MCP integrations via Tools. Although I am not understand how the rest of the MCP resources fit into the Rig Architecture (e.g. Prompts and Resources).
> 
> Looking at the Ollama docs, perhaps a list of tools used needs to be eventually sent on the completion request as it looks like Rig's architecture suggests that multiple Tools could be requested by the model for any given prompt.
> 
> In my case I made some embarrassing hacks that worked for me but I am sure are at a professional level for this project.
> 
> As I am poor (8GB VRAM), I am testing the following models where, with my patches, I have been successful :
> 
> * llama3.2:3b
> * qwen3:4b
> * qwen3:8b

Some of the more popular providers can request multiple tools to be used, yeah (OpenAI/Claude being a couple of the big examples of this).

re: MCP resources: within Rig, they're basically just tools that you can add to your agent(s). I've written up a guide [here](https://dev.to/joshmo_dev/using-model-context-protocol-with-rig-m7o) that you can take a look at. There is a docs PR that is currently pending, but until then the resources to use it are basically already there. Once `rmcp` is finally taken over by the official MCP SDK, we'll be switching over to use that (and the public API should still roughly remain the same).

**Review by cvauclair — APPROVED** [review]

File: rig-core/src/providers/ollama.rs [hunk 2]
```diff
@@ -615,6 +613,24 @@ impl TryFrom<crate::message::Message> for Message {
...
+
+                            let content = OneOrMany::many(content).map_err(|x| {
+                                MessageError::ConversionError(format!(
+                                    "Couldn't make a OneOrMany from a list of tool results: {x}"
+                                ))
+                            })?;
+
+                            return Ok(Message::ToolResult {
+                                name: result.id,
+                                content: content.first().text,
```
Comment (benaiad) [inline rig-core/src/providers/ollama.rs:631]: I ran into an issue where Ollama calls multiple tools, and while the logs show all tools being invoked, only one result is returned. I suspect this is due to `content.first()` dropping the other tool responses.

Comment (joshua-mo-143) [reply rig-core/src/providers/ollama.rs:631]: Opened a new issue, I'll have a look into it and try to fix it over the next couple of days if I don't get around to it by eod

Comment (benaiad) [reply rig-core/src/providers/ollama.rs:631]: Thanks, appreciate it 🙏
