### PR TITLE
bug(rig-959): Documents in Huggingface are not converted properly

### LINKED ISSUE #852: bug: Documents in Huggingface are not converted properly
- [x] I have looked for existing issues (including closed) about this

## Bug Report

A follow up to #848. We should make sure that documents are converted to prompt texts or are otherwise somehow included in the request.

### PR DESCRIPTION
**Pull request by FayCarsons**
Fixes #852

### CODE REVIEW

**Comment by joshua-mo-143** [comment]
It looks like we need to add a `StringLiteral` or similar variant to `DocumentSourceKind`. 

`UserContent::document()` automatically assumes the content is base64-encoded. This is an issue because `CompletionRequest::normalized_documents()` automatically tries to convert every document into a base64 encoded string document, which can confuse the model.

File: rig-core/src/providers/huggingface/completion.rs [hunk 1]
```diff
@@ -305,6 +316,12 @@ impl TryFrom<message::Message> for Vec<Message> {
                                     image_url: ImageUrl { url },
                                 })
                             }
+                            message::UserContent::Document(message::Document {
+                                data: message::DocumentSourceKind::Raw(raw), ..
+                            }) => {
+                                let text = String::from_utf8_lossy(raw.as_slice()).into();
+                                Ok(UserContent::Text { text })
+                            }
```
Comment (joshua-mo-143) [inline rig-core/src/providers/huggingface/completion.rs:324]: document snippet needs adding here too

**Review by joshua-mo-143 — CHANGES_REQUESTED** [review]
1 change required then merge
