### PR TITLE
chore(rig-963): fix feature regression in AWS bedrock

### LINKED ISSUE #857: chore: fix feature regression in AWS bedrock
> Bedrock supports Base64 encoded and raw binary documents, and with this change we have just Base64.
> 
> Maybe this was minor oversight, but it's a regression.
> 
> 
> 
> @joshua-mo-143  

 _Originally posted by @mkranjac in [1f91b09](https://github.com/0xPlaygrounds/rig/commit/1f91b09343cd34e7ceabaf3afc97fc6e56401218#r166446890)_

### PR DESCRIPTION
**Pull request by FayCarsons**
Fixes #857

### CODE REVIEW

File: rig-bedrock/src/types/document.rs [hunk 1]
```diff
@@ -27,16 +27,26 @@ impl TryFrom<RigDocument> for aws_bedrock::DocumentBlock {
...
+                return Err(CompletionError::RequestError(
+                    "File URLs not supported".into(),
+                ));
+            }
+            DocumentSourceKind::Unknown => {
+                return Err(CompletionError::RequestError("Document has no body".into()));
+            }
+            _ => {
+                return Err(CompletionError::RequestError(
+                    "Unsupported document kind".into(),
```
Comment (joshua-mo-143) [inline rig-bedrock/src/types/document.rs]: Would be useful to have the Debug impl for the document here, as it means we can essentially fold the URL variant back into it (and I guess maybe the unknown one as well? but yeah):

```rust
 doc => {
                return Err(CompletionError::RequestError(
                    format!("Undocumented document kind: {doc:?}").into()
Comment
                ));
            }
```
